config/routes.rb
Releaseme::Application.routes.draw do

  

  resources :channels do
    resources :applications do
      member do
        put :move_up, :move_down
      end
      
    end
  end

  resources :environments
  resources :deliveries

  resources :projects do
    resources :versions do
      resources :deliveries do
        member do
          post ':event' => 'deliveries#transition', :as => "transition"
        end
      end
    end
  end

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  validates_uniqueness_of :name
  
  has_many :applications, :order => :position, :dependent => :restrict
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  # GET /channels
  # GET /channels.json
  def index
    @channels = Channel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @channels }
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel = Channel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/new
  # GET /channels/new.json
  def new
    @channel = Channel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/1/edit
  def edit
    @channel = Channel.find(params[:id])
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = Channel.new(params[:channel])

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render json: @channel, status: :created, location: @channel }
      else
        format.html { render action: "new" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.json
  def update
    @channel = Channel.find(params[:id])

    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :ok }
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= simple_form_for(@channel) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
  </div>

  <div class="actions">
    <%= link_to "Cancel", projects_path, :class => "btn" %> or 
    <%= f.button :submit, :class => "primary" %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<div class="page-header">
  <h2>Listing channels</h2>
</div>

<% if @channels.any? %>
  <table class="zebra-striped">
    <tr>
      <th>Name</th>
      <th>Administration</th>
    </tr>

  <% @channels.each do |channel| %>
    <tr>
      <td><%= link_to channel.name, channel_path(channel) %></td>
      <td><%= link_to 'Edit', edit_channel_path(channel) %>&nbsp;|&nbsp;
      <%= link_to 'Destroy', channel, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </table>
<% else %>
  <p>No channel at this time</p>
<% end %>

<div class="well">
  <%= link_to 'New Channel', new_channel_path, :class => "btn primary" %>
</div>

app/views/channels/new.html.erb
<div class="page-header">
  <h2>New channel</h2>
</div>

<div class="row">
  <div class="span4 columns">
    <p>
    Channels define a stack of applications. Usualy from developement to production systems.
    You shouls define at least one channel for your project to track application evolution
    Channels are composed of environments.
    </p>
  </div>
  <div class="span12 columns">
    <%= render 'form' %>
  </div>
</div>

app/views/channels/show.html.erb
<div class="page-header">
  <h2>Composition of channel <%= @channel.name %></h2>
</div>

<div class="row">
  <div class="span4 columns">
    <p>
    Add environment to your channel here. An environment can be assigned to only one chanel.
    </p>
  </div>
  <div class="span12 columns">
    <p id="notice"><%= notice %></p>
    <table class="zebra-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Order</th>
          <th>Administration</th>
        </tr>
      </thead>
      <tbody>
        <% @channel.applications.each do |app| %>
          <tr>
            <td><%= app.environment.name %></td>
            <td><%= app.position %></td>
            <td><%= link_to "Up", app.first? ? "#" : move_up_channel_application_path(@channel,app), :method => :put,
                            :class => "btn #{"disabled" if app.first?}" %>
            <%= link_to "Down", app.last? ? "#" : move_down_channel_application_path(@channel,app), :method => :put, 
                        :class => "btn #{"disabled" if app.last?}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="well">
       <%= link_to 'Add an environement', new_channel_application_path(@channel), :class => "btn primary" %> or
      <%= link_to 'Back to Channels', channels_path, :class => "btn" %>
    </div>
   
  </div>
</div>