config/routes.rb
Releaseme::Application.routes.draw do

  

  resources :channels do
    resources :applications do
      member do
        put :move_up, :move_down
      end
      
    end
  end

  resources :environments
  resources :deliveries

  resources :projects do
    resources :versions do
      resources :deliveries do
        member do
          post ':event' => 'deliveries#transition', :as => "transition"
        end
      end
    end
  end

end

app/models/application.rb
class Application < ActiveRecord::Base
  validates_presence_of :channel_id
  validates_presence_of :environment_id
  belongs_to :channel
  belongs_to :environment
  
  validates_uniqueness_of :environment_id
  
  acts_as_list :scope => :channel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    @channel = Channel.find(params[:channel_id])
    @application = @channel.applications.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    @channel = Channel.find(params[:channel_id])
    @application = Application.new(params[:application])
    @application.channel = @channel

    respond_to do |format|
      if @application.save
        format.html { redirect_to @channel, notice: 'Application was successfully created.' }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applications/1
  # PUT /applications/1.json
  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def move_up
    @channel = Channel.find(params[:channel_id])
    @app = @channel.applications.find(params[:id])
    
    @app.move_higher
    respond_to do |format|
      format.html{redirect_to @channel}
    end
  end
  
  def move_down
    @channel = Channel.find(params[:channel_id])
    @app = @channel.applications.find(params[:id])
    
    @app.move_lower
    respond_to do |formate|
      format.html{redirect_to @channel}
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= simple_form_for(@application, :url => channel_applications_path(@channel.id)) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.association :environment %>
  </div>

  <div class="actions">
    <%= link_to "Back to #{@channel.name}", channel_path(@channel), :class => "btn" %> or 
    <%= f.button :submit, :class => "primary" %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<div class="page-header">
  <h2>Listing applications</h2>
</div>


<table class="zebra-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= link_to application.name, application_path(@application) %></td>
        <td><%= link_to 'Edit', edit_application_path(channel) %>&nbsp;|&nbsp;
        <%= link_to 'Destroy', application, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="well">
  <%= link_to 'New application', new_application_path, :class => "btn primary" %>
</div>

app/views/applications/new.html.erb
<div class="page-header">
  <h2>New application for channel <%= @channel.name %></h2>
</div>



<div class="row">
  <div class="span4 columns">
    <p>
    description goes here
    </p>
  </div>
  <div class="span12 columns">
    <%= render 'form' %>
  </div>
</div>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>