config/routes.rb
Releaseme::Application.routes.draw do

  

  resources :channels do
    resources :applications do
      member do
        put :move_up, :move_down
      end
      
    end
  end

  resources :environments
  resources :deliveries

  resources :projects do
    resources :versions do
      resources :deliveries do
        member do
          post ':event' => 'deliveries#transition', :as => "transition"
        end
      end
    end
  end

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  validates_presence_of :version_id
  validates_presence_of :application_id
  validates_uniqueness_of :application_id, :scope => :version_id
  
  belongs_to :version
  belongs_to :application
  has_one :environment, :through => :application
  
  scope :for_app, lambda{|app| where(:application_id => app.id)}
  
  
  state_machine :initial => :created do
    
    event :ask_deliver do
      transition :created => :asked, :if => :environment_asked?
    end
    
    event :deliver do
      transition :created  => :delivered, :if => :previous_delivery_validated?, :unless => :environment_asked?
      transition :asked => :delivered, :if => :environment_asked?
    end
    
    event :validate do
      transition :delivered => :validated
    end
    
    event :cancel do
      transition :delivered => :canceld
    end
  end
  
  
  def previous_delivery_validated?
    return true if self.application.first?
    prev = self.class.for_app(self.application.higher_item).where(:version_id => self.version_id).first
    return prev ? prev.validated? : false
  end
  
  def environment_asked?
    self.environment.ask_deliver
  end
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  # GET /deliveries
  # GET /deliveries.json
  def index
    @deliveries = Delivery.joins(:version, :environment).where(:environments => {:ask_deliver => true},
                                  :deliveries => {:state => :asked}).all
    @grouped = @deliveries.group_by do |del|
      del.environment
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deliveries }
    end
  end

  # GET /deliveries/1
  # GET /deliveries/1.json
  def show
    @delivery = Delivery.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @delivery }
    end
  end

  # GET /deliveries/new
  # GET /deliveries/new.json
  def new
    @project= Project.find(params[:project_id]) if params[:project_id]
    @delivery = @project ? @project.deliveries.build : Delivery.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @delivery }
    end
  end

  # GET /deliveries/1/edit
  def edit
    @delivery = Delivery.find(params[:id])
  end

  # POST /deliveries
  # POST /deliveries.json
  def create
    @version = Version.find(params[:version_id])
    @delivery = Delivery.new(params[:delivery])
    @delivery.version = @version
    respond_to do |format|
      if @delivery.save
        format.html { redirect_to project_version_path(@version.project.id, @version.id) , notice: 'Delivery was successfully created.' }
        format.json { render json: @delivery, status: :created, location: @delivery }
      else
        format.html { redirect_to project_version_path(@version.project.id, @version.id) }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deliveries/1
  # PUT /deliveries/1.json
  def update
    @delivery = Delivery.find(params[:id])

    respond_to do |format|
      if @delivery.update_attributes(params[:delivery])
        format.html { redirect_to @delivery, notice: 'Delivery was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def transition
    @project = Project.find(params[:project_id])
    @del = Delivery.find(params[:id])
    
    @del.fire_events(params[:event].to_sym)
    respond_to do |format|
      format.html {redirect_to project_version_path(@del.version.project.id, @del.version.id)}
    end
  end

  # DELETE /deliveries/1
  # DELETE /deliveries/1.json
  def destroy
    @delivery = Delivery.find(params[:id])
    @delivery.destroy

    respond_to do |format|
      format.html { redirect_to @delivery.project ? @delivery.project : deliveries_url }
      format.json { head :ok }
    end
  end
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
  def deliveries_state_for(delivery)
    content_tag(:span, delivery ? delivery.state : "N/A", :class => "label")
  end
  
  def delivery_transitions_form(delivery, event)
    simple_form_for(Delivery.new,
                        :url => transition_project_version_delivery_path(@project.id, @version.id, delivery.id, event)) do |f|
      f.button :submit, :value => event, :class => "btn primary"
    end
  end
end

app/views/deliveries/_form.html.erb
<%= simple_form_for(@delivery) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :need_label %>
    <%= f.input :description %>
    <%= f.input :project_id, :as => :hidden %>
  </div>

  <div class="actions">
    <%= link_to "Cancel", project_path(@project), :class => "btn" %> or
    <%= f.button :submit, :class => "primary" %>
  </div>
<% end %>

app/views/deliveries/_project_deliveries.html.erb
<% if deliveries.any? %>
  <table class="zebra-striped">
    <thead>
    <tr>
      <th>Description</th>
      <% @envs.each do |env| %>
        <th><%= env.name %></th>
      <% end %>
      <th>Administration</th>
    </tr>
    </thead>
    <tbody>
      <% deliveries.each do |del| %>
        <tr>
          <td><%= del.description %></td>
          <% @envs.each do |env| %>
            <td>
              <% if del.environment  == env %>
                <% if del.state_events.any? %>
                  <% del.state_events.each do |ev| %>
                    <%= simple_form_for(del, :url => transition_project_delivery_path(project.id, del.id, 
                                                                              ev.to_s), :method => :post,
                                                :html => {:class => "span"} ) do |f| %>
                      <%= f.button :submit, :value => ev.to_s %>
                    <% end %>
                  <% end %>
                <% else %>
                    <%= link_to del.state, "#", :class => "btn disabled" %>
                <% end %>
              <% end %>
            </td>
          <% end %>
          <td><%= link_to 'Edit', edit_project_delivery_path(@project, del) %>&nbsp;|&nbsp;
          <%= link_to 'Destroy', project_delivery_path(@project, del), confirm: 'Are you sure?', method: :delete %>            
          </td>
        </tr>
      <% end %>
    </tbody>
  
  </table>
<% else %>
  <p>No deliveries for this project</p>
<% end %>

app/views/deliveries/edit.html.erb
<h1>Editing delivery</h1>

<%= render 'form' %>

<%= link_to 'Show', @delivery %> |
<%= link_to 'Back', deliveries_path %>

app/views/deliveries/index.html.erb
<div class="page-header">
  <h2>Listing deliveries</h2>
</div>

<% @grouped.each do |environment, deliveries| %>
  <h3><%= environment.name %></h3>
  <table>
    <thead>
      <tr>
        <th>Project</th>
        <th>Version</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% deliveries.each do |delivery| %>
        <tr>
          <td><%= delivery.version.project.name %></td>
          <td><%= delivery.version.version %></td>
          <td><%= delivery.state %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/deliveries/new.html.erb
<div class="page-header">
  <h2>New delivery</h2>
</div>

<%= render 'form' %>

app/views/deliveries/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_delivery_path(@delivery) %> |
<%= link_to 'Back', deliveries_path %>