config/routes.rb
Releaseme::Application.routes.draw do

  

  resources :channels do
    resources :applications do
      member do
        put :move_up, :move_down
      end
      
    end
  end

  resources :environments
  resources :deliveries

  resources :projects do
    resources :versions do
      resources :deliveries do
        member do
          post ':event' => 'deliveries#transition', :as => "transition"
        end
      end
    end
  end

end

app/models/version.rb
class Version < ActiveRecord::Base
  validates_presence_of :channel_id, :project_id
  belongs_to :project
  belongs_to :channel
  has_many :deliveries, :dependent => :destroy
  
  scope :for_channel,  lambda{|channel| where(:channel_id => channel.id) }
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  # GET /versions
  # GET /versions.json
  def index
    @versions = Version.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @versions }
    end
  end

  # GET /versions/1
  # GET /versions/1.json
  def show
    @project = Project.find(params[:project_id])
    @version = @project.versions.where(:id => params[:id]).first
    @applications = @version.channel.applications.joins(:environment)
    @deliveries = @version.deliveries.group_by(&:application)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @version }
    end
  end

  # GET /versions/new
  # GET /versions/new.json
  def new
    @project = Project.find(params[:project_id])
    @version = @project.versions.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @version }
    end
  end

  # GET /versions/1/edit
  def edit
    @version = Version.find(params[:id])
    @project = Project.find(params[:project_id])
  end

  # POST /versions
  # POST /versions.json
  def create
    @project = Project.find(params[:project_id])
    @version = Version.new(params[:version])
    @version.project = @project

    respond_to do |format|
      if @version.save
        format.html { redirect_to [@project,@version], notice: 'Version was successfully created.' }
        format.json { render json: @version, status: :created, location: @version }
      else
        format.html { render action: "new" }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /versions/1
  # PUT /versions/1.json
  def update
    @project = Project.find(params[:project_id])
    @version = Version.find(params[:id])

    respond_to do |format|
      if @version.update_attributes(params[:version])
        format.html { redirect_to [@project,@version], notice: 'Version was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /versions/1
  # DELETE /versions/1.json
  def destroy
    @project = Project.find(params[:project_id])
    @version = Version.find(params[:id])
    @version.destroy

    respond_to do |format|
      format.html { redirect_to @project }
      format.json { head :ok }
    end
  end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/_application.html.erb
<tr>
  <td>
    <%= application.environment.name %>
  </td>
  <td>
    <% if @deliveries[application] %>
      <% if @deliveries[application].first.state_events.any? %>
        <% @deliveries[application].first.state_events.each do |ev| %>
          <%= delivery_transitions_form(@deliveries[application].first, ev) %>
        <% end %>
      <% else %>
        <%= deliveries_state_for(@deliveries[application].first) %>
      <% end %>
    <% elsif application.first? %>
      <%= simple_form_for(Delivery.new(:application => application),
                          :url => project_version_deliveries_path(@project.id, @version.id)) do |f| %>
        <%= f.input :application_id, :as => :hidden %>
        <%= f.button :submit, :value => "Create", :class => "btn primary" %>
      
      <% end %>
    <% end %>
  </td>
</tr>

app/views/versions/_form.html.erb
<%= simple_form_for([@project, @version]) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :version %>
    <%= f.association :channel %>
  </div>
  
  <div class="inputs">
    <%= f.input :require_label %>
    <%= f.input :description %>
  </div>

  <div class="actions">
    <%= link_to "Back to #{@project.name}", project_path(@project), :class => "btn" %> or 
    <%= f.button :submit, :class => "primary" %>
  </div>
<% end %>

app/views/versions/_project_versions.html.erb
<% if versions.any? %>
  <table class="zebra-striped">
    <thead>
    <tr>
      <th>Description</th>
      <% channel.applications.each do |app| %>
        <th><%= app.environment.name %></th>
      <% end %>
      <th>Administration</th>
    </tr>
    </thead>
    <tbody>
      <% versions.each do |version| %>
        <tr>
          <td><%= link_to version.version, project_version_path(@project, version) %></td>
          <% channel.applications.each do |app| %>
            <td><%= deliveries_state_for(version.deliveries.for_app(app).first) %></td>
          <% end %>
          <td><%= link_to 'Edit', edit_project_version_path(@project, version) %>&nbsp;|&nbsp;
          <%= link_to 'Destroy', project_version_path(@project, version), confirm: 'Are you sure?', method: :delete %>            
          </td>
        </tr>
      <% end %>
    </tbody>
  
  </table>
<% else %>
  <p>No versions for this project</p>
<% end %>

app/views/versions/edit.html.erb
<div class="page-header">
  <h2>Editing version <%= @version.version %> of project<%= @project.name %></h2>
</div>

<%= render 'form' %>

app/views/versions/index.html.erb
<div class="page-header">
  <h2>Listing versions</h2>
</div>


<table class="zebra-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @versions.each do |version| %>
      <tr>
        <td><%= link_to version.name, version_path(@version) %></td>
        <td><%= link_to 'Edit', edit_version_path(channel) %>&nbsp;|&nbsp;
        <%= link_to 'Destroy', version, confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="well">
  <%= link_to 'New version', new_version_path, :class => "btn primary" %>
</div>

app/views/versions/new.html.erb
<div class="page-header">
  <h2>New version for <%= @project.name %></h2>
</div>



<div class="row">
  <div class="span4 columns">
    <p>Version represent each evolution of a project. It can be bug fix patches or new feature. 
      But each time you change somthing in your project and you want to deliver it you should create a version.
    </p>
  </div>
  <div class="span12 columns">
    <%= render 'form' %>
  </div>
</div>

app/views/versions/show.html.erb
<div class="page_header">
  <h2>
    <%= @project.name %> : v<%= @version.version %>
    <small><%= @version.channel.name %></small>
  </h2>
</div>

<p id="notice"><%= notice %></p>

<h3>General informations</h3>
<div>
  <% if @version.require_label? %>
    <strong>This version require a label delivery</strong>
  <% else %>
    No label are required.
  <% end %>
  <p>
    <%= @version.description %>
  </p>
</div>


<h3>Deliveries</h3>
<div class="row">
  <div class="span6">
    <h4>Status</h4>
    <table class="zebra-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <%= render :partial => "application", :collection => @applications %>
      </tbody>
    </table>
  </div>
  <div class="span10">
    <h4>History</h4>
  </div>
</div>

<div class="well">
  <%= link_to "Back to #{@project.name}", project_path(@project), :class => "btn" %>
</div>